name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Insall deps
        run: sudo apt-get install make g++ pkg-config libevent-dev libglfw3-dev libglew-dev
      - name: Build
        run: make
